blank_issues_enabled: false
contact_links:
  - name: HelpChat Discord
    url: https://discord.gg/helpchat
    about: Please join our Discord for faster support.
  - name: Wiki
    url: https://wiki.helpch.at/
    about: Check out our wiki about various plugins including PlaceholderAPI.
  - name: Hastebin
    url: https://paste.helpch.at
    about: Use our Hastebin-site for sharing errors and configuration files.
